### ISSUE TITLE
Error: Cannot find module '/github/workspace/index'

### ISSUE THREAD

**Issue by tdeekens** [generates/changeset-action#39]
👋 Hi,

thanks for the GitHub Action. It looked really promising so I wanted to adopt it paired with Renovate. I ran into a small issue.

When the Action runs I see this error:

```txt
Error: Cannot find module '/github/workspace/index'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1030:15)
    at Function.Module._load (internal/modules/cjs/loader.js:899:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
```

I am not really sure how to approach it or what do to about it. You can find the run here: https://github.com/tdeekens/flopflip/pull/1318/checks?check_run_id=1436158857

The setup of the action is quite simple in 

```yaml
name: Changeset
on:
  pull_request:
    types: [labeled]
jobs:
  changeset:
    if: ${{ github.event.label.name == '🤖 Dependencies' }}
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Read .nvmrc
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)
        id: nvm

      - name: Setup Node (uses version in .nvmrc)
        uses: actions/setup-node@v1
        with:
          node-version: '${{ steps.nvm.outputs.NVMRC }}'

      - name: Changeset
        uses: generates/changeset-action@v2.0.1

      - name: Commit changes
        uses: EndBug/add-and-commit@v5
        with:
          author_name: Tobias Deekens
          author_email: nerd@tdeekens.name
          message: "chore: add changeset"
          add: ".changeset/*.md"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

Any idea what could cause this? Thanks a lot!
